# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        ########## Font ##########
        mainwindow_font = QFont('Arial')

        main_btn_font = QFont('Arial')
        main_btn_font.setBold(True)
        main_btn_font.setPointSize(12)

        home_font = QFont('Arial')
        home_font.setBold(True)
        home_font.setPointSize(18)

        heading_1_font = QFont('Arial')
        heading_1_font.setBold(True)
        heading_1_font.setPointSize(16)

        heading_2_font = QFont("Arial")
        heading_2_font.setBold(True)
        heading_2_font.setPointSize(12)

        normal_font = QFont("Arial")
        normal_font.setPointSize(12)


        ########## Mainwindow setup ##########
        MainWindow.setWindowTitle("AnimalAccML")
        MainWindow.setFixedSize(1200, 850)
        MainWindow.setFont(mainwindow_font)
        MainWindow.setWindowIcon(QIcon("images/logo.png"))

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QRect(0, 40, 1200, 810))
        font = QFont()
        font.setPointSize(12)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")


        ########## Menu buttons ##########
        self.home_btn = QPushButton("Home", self.centralwidget)
        self.home_btn.setGeometry(QRect(0, 0, 200, 40))
        self.home_btn.setFont(main_btn_font)
        self.home_btn.setStyleSheet("background-color: rgb(224, 224, 224)") # color codes: https://www.rapidtables.com/web/color/RGB_Color.html

        self.ManageProject_btn = QPushButton("Manage Projects", self.centralwidget)
        self.ManageProject_btn.setGeometry(QRect(200, 0, 200, 40))
        self.ManageProject_btn.setFont(main_btn_font)
        self.ManageProject_btn.setStyleSheet("background-color: rgb(224, 224, 224)")

        self.DataPreprocessing_btn = QPushButton("Preprocess Data", self.centralwidget)
        self.DataPreprocessing_btn.setGeometry(QRect(400, 0, 200, 40))
        self.DataPreprocessing_btn.setFont(main_btn_font)
        self.DataPreprocessing_btn.setStyleSheet("background-color: rgb(224, 224, 224)")

        self.ModelDevelopment_btn = QPushButton("Develop Models", self.centralwidget)
        self.ModelDevelopment_btn.setGeometry(QRect(600, 0, 200, 40))
        self.ModelDevelopment_btn.setFont(main_btn_font)
        self.ModelDevelopment_btn.setStyleSheet("background-color: rgb(224, 224, 224)")

        self.BehaviorAnalysis_btn = QPushButton("Analyze Behavior", self.centralwidget)
        self.BehaviorAnalysis_btn.setGeometry(QRect(800, 0, 200, 40))
        self.BehaviorAnalysis_btn.setFont(main_btn_font)
        self.BehaviorAnalysis_btn.setStyleSheet("background-color: rgb(224, 224, 224)")


        ########## Home page ##########
        self.page_home = QWidget()
        self.page_home.setStyleSheet("background-color: white")

        self.image_cover = QLabel(self.page_home)
        self.image_cover.setGeometry(QRect(50, 60, 654, 645))
        self.image_cover.setPixmap(QPixmap("images/AnimalAccML_cover.png"))
        self.image_cover.setScaledContents(True)

        self.label_home = QLabel(self.page_home)
        self.label_home.setGeometry(QRect(730, 80, 450, 500))
        self.label_home.setFont(home_font)
        self.label_home.setStyleSheet("line-height:200")
        self.label_home.setText("AnimalAccML: \nA graphical user interface for customized machine learning model development and "
                                "animal behavior analysis based on triaxial accelerometer data")
        self.label_home.setWordWrap(True)
        self.label_home.setScaledContents(True)
        self.stackedWidget.addWidget(self.page_home)


        ########## Manage Project page ##########
        self.page_ManageProject = QWidget()
        self.page_ManageProject.setLayoutDirection(Qt.RightToLeft)

        self.label_CreateNewProject = QLabel("Create a new project", self.page_ManageProject)
        self.label_CreateNewProject.setGeometry(QRect(10, 55, 400, 40))
        self.label_CreateNewProject.setFont(heading_1_font)

        self.PushButton_ProjectName = QPushButton("Project name", self.page_ManageProject)
        self.PushButton_ProjectName.setGeometry(150, 115, 200, 40)
        self.PushButton_ProjectName.setFont(normal_font)

        self.LineEdit_ProjectName = QLineEdit(self.page_ManageProject)
        self.LineEdit_ProjectName.setGeometry(QRect(390, 115, 650, 40))
        self.LineEdit_ProjectName.setFont(normal_font)

        self.PushButton_ExperimenterName = QPushButton("Experimenter name", self.page_ManageProject)
        self.PushButton_ExperimenterName.setGeometry(150, 185, 200, 40)
        self.PushButton_ExperimenterName.setFont(normal_font)

        self.LineEdit_ExperimenterName = QLineEdit(self.page_ManageProject)
        self.LineEdit_ExperimenterName.setGeometry(QRect(390, 185, 650, 40))
        self.LineEdit_ExperimenterName.setFont(normal_font)

        self.PushButton_Date = QPushButton("Date (MMDDYY)", self.page_ManageProject)
        self.PushButton_Date.setGeometry(150, 255, 200, 40)
        self.PushButton_Date.setFont(normal_font)

        self.LineEdit_Date = QLineEdit(self.page_ManageProject)
        self.LineEdit_Date.setGeometry(QRect(390, 255, 650, 40))
        self.LineEdit_Date.setFont(normal_font)

        self.PushButton_RowDataDirectory = QPushButton("Row data directory", self.page_ManageProject)
        self.PushButton_RowDataDirectory.setGeometry(150, 325, 200, 40)
        self.PushButton_RowDataDirectory.setFont(normal_font)

        self.LineEdit_RowDataDirectory = QLineEdit(self.page_ManageProject)
        self.LineEdit_RowDataDirectory.setGeometry(QRect(390, 325, 650, 40))
        self.LineEdit_RowDataDirectory.setFont(normal_font)

        self.PushButton_Create = QPushButton("Create the project", self.page_ManageProject)
        self.PushButton_Create.setGeometry(150, 420, 890, 40)
        self.PushButton_Create.setFont(normal_font)

        self.SeparationLine_ManageProject = QFrame(self.page_ManageProject)
        self.SeparationLine_ManageProject.setGeometry(QRect(0, 500, 1200, 15))
        self.SeparationLine_ManageProject.setLineWidth(5)
        self.SeparationLine_ManageProject.setFrameShape(QFrame.HLine)
        self.SeparationLine_ManageProject.setFrameShadow(QFrame.Sunken)

        self.label_loadProject = QLabel("Load an existing project", self.page_ManageProject)
        self.label_loadProject.setGeometry(QRect(10, 540, 400, 40))
        self.label_loadProject.setFont(heading_1_font)

        self.PushButton_Browse = QPushButton("Browse", self.page_ManageProject)
        self.PushButton_Browse.setGeometry(QRect(150, 610, 890, 40))
        self.PushButton_Browse.setFont(normal_font)

        self.PushButton_Loading = QPushButton("Load the project", self.page_ManageProject)
        self.PushButton_Loading.setGeometry(QRect(150, 700, 890, 40))
        self.PushButton_Loading.setFont(normal_font)
        self.stackedWidget.addWidget(self.page_ManageProject)


        ########## Data Preprocessing page ##########
        self.page_DataPreprocessing = QWidget()
        self.label_FeatureExtraction = QLabel("Feature Extraction", self.page_DataPreprocessing)
        self.label_FeatureExtraction.setGeometry(QRect(10, 50, 200, 40))
        self.label_FeatureExtraction.setFont(heading_1_font)

        self.PushButton_SamplingRate = QPushButton("Sampling rate", self.page_DataPreprocessing)
        self.PushButton_SamplingRate.setGeometry(QRect(160, 100, 200, 40))
        self.PushButton_SamplingRate.setFont(normal_font)

        self.LineEdit_SamplingRate = QLineEdit(self.page_DataPreprocessing)
        self.LineEdit_SamplingRate.setGeometry(QRect(400, 100, 650, 40))
        self.LineEdit_SamplingRate.setFont(normal_font)

        self.PushButton_WindowSize = QPushButton("Window size", self.page_DataPreprocessing)
        self.PushButton_WindowSize.setGeometry(QRect(160, 180, 200, 40))
        self.PushButton_WindowSize.setFont(normal_font)

        self.LineEdit_WindowSize = QLineEdit(self.page_DataPreprocessing)
        self.LineEdit_WindowSize.setGeometry(QRect(400, 180, 650, 40))
        self.LineEdit_WindowSize.setFont(normal_font)

        self.PushButton_StepSize = QPushButton("Step size", self.page_DataPreprocessing)
        self.PushButton_StepSize.setGeometry(QRect(160, 260, 200, 40))
        self.PushButton_StepSize.setFont(normal_font)

        self.LineEdit_StepSize = QLineEdit(self.page_DataPreprocessing)
        self.LineEdit_StepSize.setGeometry(QRect(400, 260, 650, 40))
        self.LineEdit_StepSize.setFont(normal_font)

        self.PushButton_StartExtraction = QPushButton("Start the extraction", self.page_DataPreprocessing)
        self.PushButton_StartExtraction.setGeometry(QRect(160, 360, 890, 40))
        self.PushButton_StartExtraction.setFont(normal_font)

        self.SeparationLine_DataPreprocessing = QFrame(self.page_DataPreprocessing)
        self.SeparationLine_DataPreprocessing.setGeometry(QRect(0, 440, 1200, 15))
        self.SeparationLine_DataPreprocessing.setLineWidth(5)
        self.SeparationLine_DataPreprocessing.setFrameShape(QFrame.HLine)
        self.SeparationLine_DataPreprocessing.setFrameShadow(QFrame.Sunken)

        self.label_DataCleaning = QLabel("Data Cleaning", self.page_DataPreprocessing)
        self.label_DataCleaning.setGeometry(QRect(10, 470, 200, 40))
        self.label_DataCleaning.setFont(heading_1_font)

        self.PushButton_CheckDataBalance = QPushButton("Check data balance", self.page_DataPreprocessing)
        self.PushButton_CheckDataBalance.setGeometry(QRect(160, 530, 890, 40))
        self.PushButton_CheckDataBalance.setFont(normal_font)

        self.PushButton_ClassNames = QPushButton("Names of combined classes", self.page_DataPreprocessing)
        self.PushButton_ClassNames.setGeometry(QRect(160, 610, 240, 40))
        self.PushButton_ClassNames.setFont(normal_font)

        self.LineEdit_ClassNames = QLineEdit(self.page_DataPreprocessing)
        self.LineEdit_ClassNames.setGeometry(QRect(420, 610, 630, 40))
        self.LineEdit_ClassNames.setFont(normal_font)

        self.PushButton_StartCleaning = QPushButton("Start the cleaning", self.page_DataPreprocessing)
        self.PushButton_StartCleaning.setGeometry(QRect(160, 700, 890, 40))
        self.PushButton_StartCleaning.setFont(normal_font)
        self.stackedWidget.addWidget(self.page_DataPreprocessing)


        ########## Model Development page ##########
        self.page_ModelDevelopment = QWidget()
        self.PushButton_ModelSelection = QPushButton("Select a model", self.page_ModelDevelopment)
        self.PushButton_ModelSelection.setGeometry(QRect(160, 60, 200, 40))
        self.PushButton_ModelSelection.setFont(normal_font)

        self.LineEdit_ModelSelection = QLineEdit(self.page_ModelDevelopment)
        self.LineEdit_ModelSelection.setGeometry(QRect(400, 60, 650, 40))
        self.LineEdit_ModelSelection.setFont(normal_font)

        self.PushButton_TrainValRatio = QPushButton("Validation ratio", self.page_ModelDevelopment)
        self.PushButton_TrainValRatio.setGeometry(QRect(160, 120, 200, 40))
        self.PushButton_TrainValRatio.setFont(normal_font)

        self.LineEdit_TrainValRatio = QLineEdit(self.page_ModelDevelopment)
        self.LineEdit_TrainValRatio.setGeometry(QRect(400, 120, 650, 40))
        self.LineEdit_TrainValRatio.setFont(normal_font)

        self.PushButton_StartTraining = QPushButton("Start the model training", self.page_ModelDevelopment)
        self.PushButton_StartTraining.setGeometry(QRect(160, 200, 890, 40))
        self.PushButton_StartTraining.setFont(normal_font)

        self.PushButton_StartEvaluation = QPushButton("Start the evaluation", self.page_ModelDevelopment)
        self.PushButton_StartEvaluation.setGeometry(QRect(160, 280, 890, 40))
        self.PushButton_StartEvaluation.setFont(normal_font)

        self.image_ConfusionMatrix = QLabel(self.page_ModelDevelopment)
        self.image_ConfusionMatrix.setGeometry(QRect(120, 370, 512, 384))
        #self.image_ConfusionMatrix.setPixmap(QPixmap("top_view.png"))
        self.image_ConfusionMatrix.setScaledContents(True)

        self.QLabel_av_precision = QLabel("Average precision (%)", self.page_ModelDevelopment)
        self.QLabel_av_precision.setGeometry(QRect(720, 360, 170, 40))
        self.QLabel_av_precision.setFont(normal_font)

        self.QLabel_av_recall = QLabel("Average recall (%)", self.page_ModelDevelopment)
        self.QLabel_av_recall.setGeometry(QRect(720, 420, 170, 40))
        self.QLabel_av_recall.setFont(normal_font)

        self.QLabel_av_f1_score = QLabel("Average F1-score (%)", self.page_ModelDevelopment)
        self.QLabel_av_f1_score.setGeometry(QRect(720, 480, 170, 40))
        self.QLabel_av_f1_score.setFont(normal_font)

        self.QLabel_weighted_precision = QLabel("Weighted precision (%)", self.page_ModelDevelopment)
        self.QLabel_weighted_precision.setGeometry(QRect(720, 540, 170, 40))
        self.QLabel_weighted_precision.setFont(normal_font)

        self.QLabel_weighted_recall = QLabel("Weighted recall (%)", self.page_ModelDevelopment)
        self.QLabel_weighted_recall.setGeometry(QRect(720, 600, 170, 40))
        self.QLabel_weighted_recall.setFont(normal_font)

        self.QLabel_weighted_f1_score = QLabel("Weighted F1 score (%)", self.page_ModelDevelopment)
        self.QLabel_weighted_f1_score.setGeometry(QRect(720, 660, 170, 40))
        self.QLabel_weighted_f1_score.setFont(normal_font)

        self.QLabel_overall_accuracy = QLabel("Overall_accuracy (%)", self.page_ModelDevelopment)
        self.QLabel_overall_accuracy.setGeometry(QRect(720, 720, 170, 40))
        self.QLabel_overall_accuracy.setFont(normal_font)

        self.LineEdit_av_precision = QLineEdit(self.page_ModelDevelopment)
        self.LineEdit_av_precision.setGeometry(QRect(930, 360, 160, 40))
        self.LineEdit_av_precision.setFont(normal_font)

        self.LineEdit_av_recall = QLineEdit(self.page_ModelDevelopment)
        self.LineEdit_av_recall.setGeometry(QRect(930, 420, 160, 40))
        self.LineEdit_av_recall.setFont(normal_font)

        self.LineEdit_av_f1_score = QLineEdit(self.page_ModelDevelopment)
        self.LineEdit_av_f1_score.setGeometry(QRect(930, 480, 160, 40))
        self.LineEdit_av_f1_score.setFont(normal_font)

        self.LineEdit_weighted_precision = QLineEdit(self.page_ModelDevelopment)
        self.LineEdit_weighted_precision.setGeometry(QRect(930, 540, 160, 40))
        self.LineEdit_weighted_precision.setFont(normal_font)

        self.LineEdit_weighted_recall = QLineEdit(self.page_ModelDevelopment)
        self.LineEdit_weighted_recall.setGeometry(QRect(930, 600, 160, 40))
        self.LineEdit_weighted_recall.setFont(normal_font)

        self.LineEdit_weighted_f1_score = QLineEdit(self.page_ModelDevelopment)
        self.LineEdit_weighted_f1_score.setGeometry(QRect(930, 660, 160, 40))
        self.LineEdit_weighted_f1_score.setFont(normal_font)

        self.LineEdit_overall_accuracy = QLineEdit(self.page_ModelDevelopment)
        self.LineEdit_overall_accuracy.setGeometry(QRect(930, 720, 160, 40))
        self.LineEdit_overall_accuracy.setFont(normal_font)
        self.stackedWidget.addWidget(self.page_ModelDevelopment)


        ########## Behavior Analysis page ##########
        self.page_BehaviorAnalysis = QWidget()
        self.PushButton_SelectTrainedModel = QPushButton("Select the trained model", self.page_BehaviorAnalysis)
        self.PushButton_SelectTrainedModel.setGeometry(QRect(160, 60, 890, 40))
        self.PushButton_SelectTrainedModel.setFont(normal_font)

        self.PushButton_SelectAnalyzedFile = QPushButton("Select the file for analysis", self.page_BehaviorAnalysis)
        self.PushButton_SelectAnalyzedFile.setGeometry(QRect(160, 125, 890, 40))
        self.PushButton_SelectAnalyzedFile.setFont(normal_font)

        self.PushButton_LoadKeyParameters = QPushButton("Load key parameters for analysis", self.page_BehaviorAnalysis)
        self.PushButton_LoadKeyParameters.setGeometry(QRect(160, 190, 890, 40))
        self.PushButton_LoadKeyParameters.setFont(normal_font)

        self.PushButton_StartAnalysis = QPushButton("Start the analysis", self.page_BehaviorAnalysis)
        self.PushButton_StartAnalysis.setGeometry(QRect(160, 255, 890, 40))
        self.PushButton_StartAnalysis.setFont(normal_font)

        self.PushButton_VisualizeExampleResults = QPushButton("Visualize example results", self.page_BehaviorAnalysis)
        self.PushButton_VisualizeExampleResults.setGeometry(QRect(160, 320, 890, 40))
        self.PushButton_VisualizeExampleResults.setFont(normal_font)

        self.image_BehaviorBudget = QLabel(self.page_BehaviorAnalysis)
        self.image_BehaviorBudget.setGeometry(QRect(120, 390, 512, 384))
        self.image_BehaviorBudget.setScaledContents(True)

        self.QLabel_TimeBudgets = QLabel("Time budgets of top three behaviors", self.page_BehaviorAnalysis)
        self.QLabel_TimeBudgets.setGeometry(QRect(710, 400, 350, 40))
        self.QLabel_TimeBudgets.setFont(heading_2_font)

        self.QLabel_Top_1_Name = QLabel(self.page_BehaviorAnalysis)
        self.QLabel_Top_1_Name.setGeometry(QRect(710, 470, 170, 40))
        self.QLabel_Top_1_Name.setFont(normal_font)

        self.LineEdit_Top_1_Behavior = QLineEdit(self.page_BehaviorAnalysis)
        self.LineEdit_Top_1_Behavior.setGeometry(QRect(910, 470, 160, 40))
        self.LineEdit_Top_1_Behavior.setFont(normal_font)

        self.QLabel_Top_2_Name = QLabel(self.page_BehaviorAnalysis)
        self.QLabel_Top_2_Name.setGeometry(QRect(710, 560, 170, 40))
        self.QLabel_Top_2_Name.setFont(normal_font)

        self.LineEdit_Top_2_Behavior = QLineEdit(self.page_BehaviorAnalysis)
        self.LineEdit_Top_2_Behavior.setGeometry(QRect(910, 560, 160, 40))
        self.LineEdit_Top_2_Behavior.setFont(normal_font)

        self.QLabel_Top_3_Name = QLabel(self.page_BehaviorAnalysis)
        self.QLabel_Top_3_Name.setGeometry(QRect(710, 650, 170, 40))
        self.QLabel_Top_3_Name.setFont(normal_font)

        self.LineEdit_Top_3_Behavior = QLineEdit(self.page_BehaviorAnalysis)
        self.LineEdit_Top_3_Behavior.setGeometry(QRect(910, 650, 160, 40))
        self.LineEdit_Top_3_Behavior.setFont(normal_font)

        self.stackedWidget.addWidget(self.page_BehaviorAnalysis)

        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QMenuBar(MainWindow)
        # self.menubar.setGeometry(QRect(0, 0, 1200, 24))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        # self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(MainWindow)


    # def retranslateUi(self, MainWindow):
    #     _translate = QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.label.setText(_translate("MainWindow", "Please click the buttons below to update background color"))

