# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DigitalPhenotyping.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)
        # changing the background color to cyan
        MainWindow.setStyleSheet("background-color: white;")

        # define a set of variable
        self.EN = str()  # experimenter name
        self.Date = str()  # date
        self.CattleBS = str()  # cattle body score
        self.CattleID = str()  # cattle ID
        self.CattleBreed = str()  # cattle breed
        self.CattleAge = str()  # cattle age
        self.RGBPath = str()  # path for the loaded RGB image
        self.DepthPath = str()

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(0, 60, 1200, 790)
        self.stackedWidget.setObjectName("stackedWidget")

###########################################################################################
#                                Subsection: Home Page                                    #
###########################################################################################
        self.page_home = QWidget()
        self.page_home.setObjectName("page_home")
        self.label_home = QLabel(self.page_home)
        self.label_home.setGeometry(770, 150, 300, 100)
        self.label_home.setFont(QFont("Calibri", 25, QFont.Bold))
        self.label_home.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)
        self.label_home.setWordWrap(True)
        self.label_home.setObjectName("label_home")
        self.label_home_2 = QLabel(self.page_home)
        self.label_home_2.setGeometry(770, 200, 350, 300)
        self.label_home_2.setFont(QFont("Calibri", 18))
        self.label_home_2.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)
        self.label_home_2.setWordWrap(True)
        self.label_home_2.setObjectName("label_home_2")
        self.image_SideView = QLabel(self.page_home)
        self.image_SideView.setGeometry(20, 100, 744, 576)
        self.stackedWidget.addWidget(self.page_home)

###########################################################################################
#                         Subsection: ProjectManagement Page                              #
###########################################################################################
        self.page_ProjectManagement = QWidget()
        self.page_ProjectManagement.setObjectName("page_ProjectManagement")
        self.line_ProjectManagement = QFrame(self.page_ProjectManagement)
        self.line_ProjectManagement.setGeometry(0, 630, 1200, 2)
        self.line_ProjectManagement.setFrameShape(QFrame.HLine)
        self.line_ProjectManagement.setObjectName("line_ProjectManagement")
        self.label_ProjectManagement = QLabel(self.page_ProjectManagement)
        self.label_ProjectManagement.setGeometry(10, 650, 1180, 100)
        self.label_ProjectManagement.setFont(QFont("Calibri", 12))
        self.label_ProjectManagement.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)
        self.label_ProjectManagement.setWordWrap(True)
        self.label_ProjectManagement.setObjectName("label_ProjectManagement")
        self.LineEdit_EN = QLineEdit(self.page_ProjectManagement)
        self.LineEdit_EN.setGeometry(180, 40, 140, 30)
        self.LineEdit_EN.setFont(QFont("Calibri", 10))
        self.stackedWidget.addWidget(self.page_ProjectManagement)


###########################################################################################
#                           Subsection: Preprocessing Page                                #
###########################################################################################
        self.page_Preprocessing = QWidget()
        self.page_Preprocessing.setObjectName("page_Preprocessing")
        self.line_Preprocessing = QFrame(self.page_Preprocessing)
        self.line_Preprocessing.setGeometry(0, 630, 1200, 2)
        self.line_Preprocessing.setFrameShape(QFrame.HLine)
        self.line_Preprocessing.setObjectName("line_Preprocessing")
        self.label_Preprocessing = QLabel(self.page_Preprocessing)
        self.label_Preprocessing.setGeometry(10, 650, 1180, 100)
        self.label_Preprocessing.setFont(QFont("Calibri", 12))
        self.label_Preprocessing.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)
        self.label_Preprocessing.setWordWrap(True)
        self.label_Preprocessing.setObjectName("label_Preprocessing")
        self.stackedWidget.addWidget(self.page_Preprocessing)

###########################################################################################
#                            Subsection: MLModeling Page                                  #
###########################################################################################
        self.page_MLModeling = QWidget()
        self.page_MLModeling.setObjectName("page_MLModeling")
        self.line_MLModeling = QFrame(self.page_MLModeling)
        self.line_MLModeling.setGeometry(0, 630, 1200, 2)
        self.line_MLModeling.setFrameShape(QFrame.HLine)
        self.line_MLModeling.setObjectName("line_MLModeling")
        self.label_MLModeling = QLabel(self.page_MLModeling)
        self.label_MLModeling.setGeometry(10, 650, 1180, 100)
        self.label_MLModeling.setFont(QFont("Calibri", 12))
        self.label_MLModeling.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)
        self.label_MLModeling.setWordWrap(True)
        self.label_MLModeling.setObjectName("label_MLModeling")
        self.stackedWidget.addWidget(self.page_MLModeling)

###########################################################################################
#                         Subsection: Behavior analysis Page                              #
###########################################################################################
        self.page_BehaviorAnalysis = QWidget()
        self.page_BehaviorAnalysis.setObjectName("page_BehaviorAnalysis")
        self.line_BehaviorAnalysis = QFrame(self.page_BehaviorAnalysis)
        self.line_BehaviorAnalysis.setGeometry(0, 630, 1200, 2)
        self.line_BehaviorAnalysis.setFrameShape(QFrame.HLine)
        self.line_BehaviorAnalysis.setObjectName("line_BehaviorAnalysis")
        self.label_BehaviorAnalysis = QLabel(self.page_BehaviorAnalysis)
        self.label_BehaviorAnalysis.setGeometry(10, 650, 1180, 100)
        self.label_BehaviorAnalysis.setFont(QFont("Calibri", 12))
        self.label_BehaviorAnalysis.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_BehaviorAnalysis.setWordWrap(True)
        self.label_BehaviorAnalysis.setObjectName("label_BehaviorAnalysis")
        self.stackedWidget.addWidget(self.page_BehaviorAnalysis)

###########################################################################################
#                                 Subsection: Help Page                                   #
###########################################################################################
        self.page_Help = QWidget()
        self.page_Help.setObjectName("page_Help")
        self.label_Help = QLabel(self.page_BehaviorAnalysis)
        self.label_Help.setGeometry(10, 650, 1180, 100)
        self.label_Help.setFont(QFont("Calibri", 12))
        self.label_Help.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)
        self.label_Help.setWordWrap(True)
        self.label_Help.setObjectName("label_Help")
        self.stackedWidget.addWidget(self.page_Help)

###########################################################################################
#                                Subsection: Main Page                                    #
###########################################################################################
        # separation line
        # self.line = QFrame(self.centralwidget)
        # self.line.setGeometry(0, 45, 1200, 2)
        # self.line.setFrameShape(QFrame.HLine)
        # self.line.setObjectName("line")

        # home btn
        self.pushButton_home = QPushButton("Home", self.centralwidget)
        self.pushButton_home.setGeometry(0, 0, 120, 40)
        self.pushButton_home.setFont(QFont("Calibri", 12, QFont.Bold))
        self.pushButton_home.setStyleSheet("background-color : light gray")
        self.pushButton_home.setObjectName("pushButton_home")

        # ProjectManagement btn
        self.pushButton_ProjectManagement = QPushButton("Project Management", self.centralwidget)
        self.pushButton_ProjectManagement.setGeometry(120, 0, 200, 40)
        self.pushButton_ProjectManagement.setFont(QFont("Calibri", 12, QFont.Bold))
        self.pushButton_ProjectManagement.setStyleSheet("background-color : light gray")
        self.pushButton_ProjectManagement.setObjectName("pushButton_ProjectManagement")

        # Preprocessing btn
        self.pushButton_Preprocessing = QPushButton("Preprocessing", self.centralwidget)
        self.pushButton_Preprocessing.setGeometry(320, 0, 140, 40)
        self.pushButton_Preprocessing.setFont(QFont("Calibri", 12, QFont.Bold))
        self.pushButton_Preprocessing.setStyleSheet("background-color : light gray")
        self.pushButton_Preprocessing.setObjectName("pushButton_Preprocessing")

        # MLModeling btn
        self.pushButton_MLModeling = QPushButton("ML Modeling", self.centralwidget)
        self.pushButton_MLModeling.setGeometry(460, 0, 140, 40)
        self.pushButton_MLModeling.setFont(QFont("Calibri", 12, QFont.Bold))
        self.pushButton_MLModeling.setStyleSheet("background-color : light gray")
        self.pushButton_MLModeling.setObjectName("pushButton_MLModeling")

        # Behavior analysis btn
        self.pushButton_BehaviorAnalysis = QPushButton("Behavior Analysis", self.centralwidget)
        self.pushButton_BehaviorAnalysis.setGeometry(600, 0, 180, 40)
        self.pushButton_BehaviorAnalysis.setFont(QFont("Calibri", 12, QFont.Bold))
        self.pushButton_BehaviorAnalysis.setStyleSheet("background-color : light gray")
        self.pushButton_BehaviorAnalysis.setObjectName("pushButton_BehaviorAnalysis")

        # Help btn
        self.pushButton_Help = QPushButton("Help", self.centralwidget)
        self.pushButton_Help.setGeometry(780, 0, 120, 40)
        self.pushButton_Help.setFont(QFont("Calibri", 12, QFont.Bold))
        self.pushButton_Help.setStyleSheet("background-color : light gray")
        self.pushButton_Help.setObjectName("pushButton_Help")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        QMetaObject.connectSlotsByName(MainWindow)


    def getEN(self):
        self.EN, ok = QInputDialog.getText(self.page_ProjectManagement, 'Text Input', 'Enter your name:')
        if ok:
            self.LineEdit_EN.setText(str(self.EN))
        return self.EN

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AccML"))
        MainWindow.setWindowIcon(QIcon("./images/logo.png"))

        # home page
        self.label_home.setText(_translate("MainWindow", "AccML:"))
        self.label_home_2.setText(
            _translate("MainWindow", "A machine learning platform for analyzing animal acceleration data"))
        self.image_SideView.setText("")
        self.image_SideView.setPixmap(QPixmap("./images/CoverPage.png"))
        self.image_SideView.setScaledContents(True)

        # ProjectManagement page
        self.label_ProjectManagement.setText(_translate("MainWindow", "Hint: ProjectManagement"))

        # Preprocessing page
        self.label_Preprocessing.setText(_translate("MainWindow", "Hint: Preprocessing"))

        # MLModeling page
        self.label_MLModeling.setText(_translate("MainWindow", "Hint: MLModeling"))

        # Behavior analysis page
        self.label_BehaviorAnalysis.setText(_translate("MainWindow", "Hint: BehaviorAnalysis"))

        # Help page
        self.label_Help.setText(_translate("MainWindow", "Hint: Help"))

