# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trials.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(240, 0, 950, 850))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.label = QtWidgets.QLabel(self.page_home)
        self.label.setGeometry(QtCore.QRect(230, 230, 311, 191))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_home)
        self.page_blue = QtWidgets.QWidget()
        self.page_blue.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.page_blue.setStyleSheet("background-color:blue")
        self.page_blue.setObjectName("page_blue")
        self.stackedWidget.addWidget(self.page_blue)
        self.page_yellow = QtWidgets.QWidget()
        self.page_yellow.setStyleSheet("background-color:yellow")
        self.page_yellow.setObjectName("page_yellow")
        self.stackedWidget.addWidget(self.page_yellow)
        self.page_red = QtWidgets.QWidget()
        self.page_red.setStyleSheet("background-color:red")
        self.page_red.setObjectName("page_red")
        self.stackedWidget.addWidget(self.page_red)
        self.Blue_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Blue_btn.setGeometry(QtCore.QRect(20, 80, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Blue_btn.setFont(font)
        self.Blue_btn.setObjectName("Blue_btn")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(220, 0, 20, 1021))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Red_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Red_btn.setGeometry(QtCore.QRect(20, 190, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Red_btn.setFont(font)
        self.Red_btn.setObjectName("Red_btn")
        self.Yellow_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Yellow_btn.setGeometry(QtCore.QRect(20, 330, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Yellow_btn.setFont(font)
        self.Yellow_btn.setObjectName("Yellow_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Please click the buttons below to update background color"))
        self.Blue_btn.setText(_translate("MainWindow", "Blue"))
        self.Red_btn.setText(_translate("MainWindow", "Red"))
        self.Yellow_btn.setText(_translate("MainWindow", "Yellow"))
